### ISSUE TITLE
Difficult packetlogging

### ISSUE THREAD

**Issue by ZroIsHere** [ApourtArtt/NosTaleSDK#22]
The idea (isnt mine) to make the client encrypt the packets in aes when sending it and decrypt when receiving it using aes or some kind of encryption

**Comment by ApourtArtt** [comment]
Is it an idea to avoid being packetlogged by injection-less packetlogger (such as [NosTale-PacketLogger](https://github.com/ApourtArtt/NosTale-PacketLogger)) ?

I already had the idea to had some anti-things (anti injection, anti OnexExplorer, changing the cryptography) and so on, the issue is it is difficult to make such a system open source (because you don't need that much reverse engineering skills if you already have the code)

For the idea how adding a cryptography on top of the game cryptography, I think the best I can do is to implement a way of adding your own cryptography, this way you can customize and it will be harder for people to find it (and I can obviously provide a default/default+encrypted version) as a basis

**Comment by ApourtArtt** [comment]
Hello @ZroIsHere 
I would like to start working on this idea. Are you able to provide a server for test purpose with a modified cryptography ? (A simple xor as a first step, for example)

**Comment by BattleTaleGH** [comment]
Hello @ApourtArtt 
If you are still looking for server for test I think I would be able to help you with that.
I am using my VDS for other purposes but if you need I can setup opennos there and give you access to server.
Feel free to add me on discord: NEEXI#6133

**Comment by ZroIsHere** [comment]
@ApourtArtt i can if u like, but not all days, tell me hours and days

**Comment by ApourtArtt** [comment]
Thank you, I contacted both of you (AA#9685)
